//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offers
    {
        public int offersId { get; set; }
        public string offersgUId { get; set; }
        public string offersName { get; set; }
        public string offersDesc { get; set; }
        public int tourId { get; set; }
        public decimal listPrice { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public int status { get; set; }
        public string userId { get; set; }
    
        public virtual TourType TourType { get; set; }
    }
}
